#!/usr/bin/env bash
# Generate secrets for Komodo Core
set -euo pipefail
# shellcheck disable=SC2034 # we dynamically loop through all envs
# shellcheck disable=SC2312 # masking return values of internal functions is okay

# source dirs.env if it exists
# we assume that dirs.env is in /etc/komodo, but setting KOMODO_DATA_DIR externally will override this
KOMODO_CONFIG_DIR_BASE="${KOMODO_CONFIG_DIR_BASE:-"/etc/komodo"}"
INITIALIZE_KOMODO_ENV_FILE="${INITIALIZE_KOMODO_ENV_FILE:-"${KOMODO_CONFIG_DIR_BASE}/initialize-komodo.env"}"
# shellcheck source=/dev/null # this file will be generated by bootstrap_komodo.sh
source "${INITIALIZE_KOMODO_ENV_FILE}" || true # ignore errors, in case it doesn't exist
# because dirs.env may have updated the variable $KOMODO_DATA_DIR, we need to re-source the dirs.env
# shellcheck source=/dev/null # this file will be generated by bootstrap_komodo.sh
source "${INITIALIZE_KOMODO_ENV_FILE}" # don't ignore errors this time

set_config_vars(){

# List of secrets to generate
PASSKEY="${PASSKEY:-"$(generate_random_bytes 48)"}"
DB_USERNAME="${DB_USERNAME:-"$(generate_random_bytes 48)"}"
DB_PASSWORD="${DB_PASSWORD:-"$(generate_random_bytes 48)"}"
WEBHOOK_SECRET="${WEBHOOK_SECRET:-"$(generate_random_bytes 48)"}"
JWT_SECRET="${JWT_SECRET:-"$(generate_random_bytes 48)"}"

# Files to write
CANARY_FILE="${CANARY_FILE:-"/etc/komodo/.secrets-have-been-initialized"}"
KOMODO_CORE_ENV_FILE="${KOMODO_CORE_ENV_FILE:-"/etc/komodo/core/core.env"}"
PERIPHERY_ENV_FILE="${PERIPHERY_ENV_FILE:-"/etc/komodo/periphery/periphery.env"}"
PASSKEY_FILE="${PASSKEY_FILE:-"/etc/komodo/core/passkey"}"
DB_PASSWORD_FILE="${DB_PASSWORD_FILE:-"/etc/komodo/core/db_password"}"
DB_USERNAME_FILE="${DB_USERNAME_FILE:-"/etc/komodo/core/db_username"}"
WEBHOOK_SECRET_FILE="${WEBHOOK_SECRET_FILE:-"/etc/komodo/core/webhook_secret"}"
JWT_SECRET_FILE="${JWT_SECRET_FILE:-"/etc/komodo/core/jwt_secret"}"

}

### functions ###
set_functions() {
## CRUD functions for env files
escape_slashes() {
    local str
    str="${1}"
    echo "${str//"/"/"\\/"}"
}

delete_env_key() {
    local key file
    key="${1}"
    file="${2}"
    sed -i -E "/^${key}=.*/d" "${file}"
}

replace_env_key() {
    local key value file
    key="$(escape_slashes "${1}")"
    value="${2}"
    file="${3}"
    sed -i -E "s/^#?${key}=.*/${key}=${value}/" "${file}"
}

add_env_key() {
    local key value file last_byte
    key="${1}"
    value="${2}"
    file="${3}"
    if [[ ! -f "${file}" ]]; then
        touch "${file}"
    fi
    # if the last byte is not newline, then >> doesn't work.
    # check if the last byte is newline, and if not, add one.
    last_byte="$(tail -c 1 "${file}" | wc -l)"
    if [[ "${last_byte}" -eq 0 ]]; then
        printf '%s\n' '' >>"${file}"
    fi
    echo "${key}=${value}" >>"${file}"
}

update_env_key() {
    local key value file
    key="${1}"
    value="${2}"
    file="${3}"
    if grep -q "^${key}=" "${file}"; then
        replace_env_key "${key}" "${value}" "${file}"
    else
        add_env_key "${key}" "${value}" "${file}"
    fi
}


update_env_key_if_not_empty() {
    local key="${1}"
    local value="${2:-}" # default to empty string
    local file="${3}"
    if [[ -n "${value}" ]]; then # if value is not empty
        update_env_key "${key}" "${value}" "${file}"
    fi
}

# Write value to file
write_secret_file() {
    local secret_file="${1}"
    local secret_value="${2}"
    local secret_file_mode="${3:-600}" # default to rw-------
    printf "%s\n" "${secret_value}" >"${secret_file}"
    chmod "${secret_file_mode}" "${secret_file}"
}

update_secret_or_env_key() {
    local key="${1}"
    local value="${2}"
    local file="${3}"
    local secret_file_var="${key}_FILE"
    if [[ -n "${!secret_file_var}" ]]; then # if secret_file is set
        write_secret_file "${!secret_file_var}" "${value}"
        delete_env_key "${key}" "${file}"
    else
        update_env_key "${key}" "${value}" "${file}"
    fi
}


# Generate random bytes
generate_random_bytes() {
    local bytes random_bytes
    bytes="${1:-48}"
    random_bytes="$(openssl rand -base64 "${bytes}")"
    printf "%s" "${random_bytes}"
}

# function that receives one parameter, uppercases it, and then loops through all variable names that start with the parameter (using bash param expansion).
update_env_files() {
    for key in \
        PASSKEY \
        DB_USERNAME \
        DB_PASSWORD \
        WEBHOOK_SECRET \
        JWT_SECRET \
    ;
     do
        local secret_file="${key}_FILE"
        local value="${!key}"
        if [[ -n "${!secret_file}" ]]; then
            write_secret_file "${!secret_file}" "${value}"
        else
            update_env_key "${key}" "${value}" "${KOMODO_CORE_ENV_FILE}"
        fi
    done

    for key in "${!PERIPHERY_VARS[@]}"; do
        local product="periphery"
        local PRODUCT="${product^^}" # uppercase
        local env_file_var="${PRODUCT}_ENV_FILE" # e.g., PERIPHERY_ENV_FILE
        local env_file="${!env_file_var}" # e.g., PERIPHERY_ENV_FILE
        value="${PERIPHERY_VARS[${key}]}"
        update_secret_or_env_key "${key}" "${value}" "${env_file}"
    done
}

}
MAIN() {
    # set functions
    set_functions
    SET_CONFIG_VARS # load variables

if [[ -f "${CANARY_FILE}" ]]; then
    echo "Secrets have already been initialized for Komodo. Exiting..."
    exit 0
else
    echo "Initializing secrets and default configuration for Komodo..."
fi

    # update env files
    update_env_files

    # touch canary file when done
    touch "${CANARY_FILE}"
    chmod 644 "${CANARY_FILE}"
}

    MAIN "$@"