---
name: Build Image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  merge_group:
  push:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  IMAGE_NAME: "homeserver"
  IMAGE_DESC: "CentOS Stream-based Homeserver-focused image"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"
  CENTOS_VERSION: "stream9"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get current date
        id: date
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail
          # save the date, because we want any generated times to match
          unixtime="$(date -u +%s)"
          # Should generate a timestamp like what is defined on the ArtifactHub documentation
          artifacthub_style="+%Y-%m-%dT%H:%M:%SZ"
          # E.G: 2022-02-08T15:38:15Z'
          # https://artifacthub.io/docs/topics/repositories/container-images/
          # https://linux.die.net/man/1/date
          echo "artifacthub_style=$(date -u ${artifacthub_style} -d @"${unixtime}")" | tee -a $GITHUB_OUTPUT
          yyyymmdd_style="+%Y%m%d"
          echo "yyyymmdd=$(date -u "${yyyymmdd_style}" -d @"${unixtime}")" | tee -a $GITHUB_OUTPUT

      - name: Generate tags
        id: tags
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail
          slash='/'
          underscore='_'
          # Generate primary and ref tags for the image
          ref_name="${{ github.ref_name }}"
          case ${{ github.event_name }} in
          "pull_request")
            # ref_name=<pr_number>/merge
            pr_number=${ref_name%%/*}
            primary_tag="latest-pr-${pr_number}"
            ref_tag="pr-${pr_number}.${{ steps.date.outputs.yyyymmdd }}"
          ;;
          "push")
            branch_name="${ref_name}"
            if [[ "${branch_name}" == "${{ github.event.repository.default_branch }}" ]]; then
              primary_tag="latest"
            else
              primary_tag="latest-${ref_name//"${slash}"/"${underscore}"}"
            fi
            ref_tag="${ref_name//"${slash}"/"${underscore}"}.${{ steps.date.outputs.yyyymmdd }}"
          ;;
          "schedule")
            primary_tag="nightly"
            ref_tag="nightly.${{ steps.date.outputs.yyyymmdd }}"
          ;;
          *)
            primary_tag="$(date '+%s')"
            ref_tag="$(date '+%s')"
          ;;
          esac
          echo "primary_tag=${primary_tag}" | tee -a $GITHUB_OUTPUT
          echo "ref_tag=${ref_tag}" | tee -a $GITHUB_OUTPUT

      - name: Image Metadata
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
        id: metadata
        with:
          tags: |
            type=raw,value=${{ steps.tags.outputs.primary_tag }}
            type=raw,value=${{ steps.tags.outputs.primary_tag }}.${{ steps.date.outputs.yymmdd }}
            type=raw,value=${{ steps.tags.outputs.ref_tag }}
            type=raw,value=${{ steps.tags.outputs.ref_tag }}.${{ steps.date.outputs.yymmdd }}
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=${{ env.CENTOS_VERSION }}
            type=raw,value=${{ env.CENTOS_VERSION }}.{{date 'YYYYMMDD'}}
            type=sha,enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=pr
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/refs/heads/main/README.md
            org.opencontainers.image.created=${{ steps.date.outputs.artifacthub_style }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/refs/heads/main/README.md
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/blob/main/Containerfile
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ env.CENTOS_VERSION }}
            io.artifacthub.package.deprecated=false
            io.artifacthub.package.keywords=bootc,centos,ublue,universal-blue
            io.artifacthub.package.license=Apache-2.0
            io.artifacthub.package.logo-url=https://avatars.githubusercontent.com/u/120078124?s=200&v=4
            io.artifacthub.package.maintainers=[{\"name\":\"tulilirockz\",\"email\":\"tulilirockz@outlook.com\"},{\"name\":\"castrojo\", \"email\": \"jorge.castro@gmail.com\"}]
            io.artifacthub.package.prerelease=false
            containers.bootc=1
          sep-tags: " "
          sep-annotations: " "

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          # Postfix image name with -custom to make it a little more descriptive
          # Syntax: https://docs.github.com/en/actions/learn-github-actions/expressions#format
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          oci: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        if: github.event_name != 'pull_request'
        id: push
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
        if: github.event_name != 'pull_request'

      - name: Sign container image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_FULL="${{ env.IMAGE_REGISTRY }}/${IMAGE_NAME}"
          for tag in ${{ steps.metadata.outputs.tags }}; do
            cosign sign -y --key env://COSIGN_PRIVATE_KEY $IMAGE_FULL:$tag
          done
        env:
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
